# ============================================================
# rag/llm_analyzer.py
#
# UPDATED FOR GRAPH RAG:
#   - Specialty-service mismatch par Graph RAG check hoga
#   - Agar service General Physician se inherit hoti hai
#     toh specialty mismatch fraud nahi hoga
#   - Baaki sari fraud reasoning SAME hai
# ============================================================
import os
from dotenv import load_dotenv

load_dotenv()
from groq import Groq

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def analyze_claim(agent1_state: dict, retrieved_policies: str) -> str:
    is_fraud = agent1_state.get('is_fraud', False)
    if is_fraud:
        return _fraud_report(agent1_state, retrieved_policies)
    else:
        return _normal_report(agent1_state, retrieved_policies)


def _normal_report(agent1_state: dict, retrieved_policies: str) -> str:

    transaction  = agent1_state.get('transaction', {})
    rel_feats    = agent1_state.get('relationship_features', {})
    overall_risk = agent1_state.get('overall_risk', 'NORMAL')

    doc_spec = rel_feats.get('doc_spec_match', 0.5)
    svc_spec = rel_feats.get('svc_spec_match', 0.5)
    diag_svc = rel_feats.get('diag_svc_match', 0.5)

    def feat_label(val):
        if val == 1.0: return "✅ NORMAL"
        if val == 0.0: return "🚨 MISMATCH"
        return "⚠️ UNKNOWN"

    prompt = f"""
You are a healthcare billing compliance expert reviewing
a transaction that has been cleared as NORMAL.

================================================================
TRANSACTION DETAILS:
================================================================
Patient ID    : {transaction.get('PATIENT_ID')}
Doctor ID     : {transaction.get('DOCTOR_ID')}
Speciality    : {transaction.get('SPECIALITY_NAME')}
Diagnosis     : {transaction.get('DIAGNOSIS')}
Service       : {transaction.get('SERVICE_DESCRIPTION')}
Service ID    : {transaction.get('SERVICE_ID')}
Overall Verdict: {overall_risk}

================================================================
CROSS-FEATURE SIGNALS:
================================================================
doc_spec_match : {doc_spec}  → {feat_label(doc_spec)}
svc_spec_match : {svc_spec}  → {feat_label(svc_spec)}
diag_svc_match : {diag_svc}  → {feat_label(diag_svc)}

================================================================
RELEVANT POLICIES (FAISS + GRAPH RAG):
================================================================
{retrieved_policies}

================================================================
GRAPH RAG — SPECIALTY MISMATCH RULE:
================================================================
Check GRAPH RAG CONTEXT above for service permissions:

CASE 1 — Service ALLOWED via direct CAN_ORDER:
  → Service is directly within this specialty's scope
  → No mismatch exists → billing is correct

CASE 2 — Service ALLOWED via INHERITS (General Physician):
  → Service is permitted for ANY licensed physician
  → Specialty mismatch is NOT a concern here
  → All licensed physicians can order general medical services

CASE 3 — Service NOT FOUND in graph:
  → Re-evaluate based on clinical context

NOTE: This check applies ONLY to specialty-service mismatch.
All other billing rules remain unchanged.
================================================================

YOUR TASK:
Write a short professional clearance report.

Respond in this EXACT format:

VERDICT: LEGITIMATE

EXECUTIVE SUMMARY:
[2-3 sentences confirming transaction is normal]

TRANSACTION ANALYSIS:
[Is service clinically appropriate? Is doctor billing correctly?
If service is inherited from General Physician, mention this.]

CLINICAL ANALYSIS:
[Explain doc_spec, svc_spec, diag_svc in plain language.]

RECOMMENDATION: APPROVE

NOTES:
[Any additional compliance notes]

================================================================
IMPORTANT DISCLAIMER:
================================================================
This report has been generated by an AI-based fraud detection
system and is intended for informational purposes only.

A qualified human reviewer must:
- Review this report carefully
- Verify all findings independently
- Make the final determination on whether fraud has occurred
- Approve, reject, or escalate this claim accordingly

This AI report does NOT constitute a final fraud verdict.
Final authority rests with the human reviewer only.
================================================================
"""

    print("Calling Groq API — normal clearance report...")
    response = client.chat.completions.create(
        model      = "llama-3.3-70b-versatile",
        max_tokens = 900,
        messages   = [
            {
                "role"   : "system",
                "content": (
                    "You are a healthcare billing compliance expert. "
                    "When Graph RAG shows a service is inherited from "
                    "General Physician, do not flag specialty mismatch. "
                    "Never mention AI models, machine learning, or detection systems."
                )
            },
            {"role": "user", "content": prompt}
        ]
    )

    report = response.choices[0].message.content
    print(f"✅ Normal clearance report generated ({len(report)} chars)")
    print("\n" + "="*55)
    print("REPORT:")
    print("="*55)
    print(report)
    return report


def _fraud_report(agent1_state: dict, retrieved_policies: str) -> str:

    transaction        = agent1_state.get('transaction', {})
    overall_risk       = agent1_state.get('overall_risk', 'Unknown')
    rel_feats          = agent1_state.get('relationship_features', {})

    doc_spec           = rel_feats.get('doc_spec_match', 0.5)
    svc_spec           = rel_feats.get('svc_spec_match', 0.5)
    diag_svc           = rel_feats.get('diag_svc_match', 0.5)

    responsible_party  = agent1_state.get('responsible_party', 'Unknown')
    primary_fraud_type = agent1_state.get('primary_fraud_type', 'Unknown')
    fraud_types        = agent1_state.get('fraud_types', [])
    confidence         = agent1_state.get('confidence', 0.0)
    reasons            = agent1_state.get('reasons', [])
    overbilling_flag   = agent1_state.get('overbilling_flag', False)
    overbilling_note   = agent1_state.get('overbilling_note', '')

    doctor_score       = agent1_state.get('updated_doctor_score', 'N/A')
    score_penalty      = agent1_state.get('doctor_score_penalty', 0)
    score_breakdown    = agent1_state.get('score_breakdown', {})
    score_status       = score_breakdown.get('score_status', 'Unknown')
    previous_frauds    = score_breakdown.get('previous_frauds', 0)

    def feat_label(val):
        if val == 1.0: return "✅ NORMAL"
        if val == 0.0: return "🚨 FRAUD SIGNAL"
        return "⚠️ UNKNOWN"

    fraud_types_text = "\n".join(f"  - {ft}" for ft in fraud_types) if fraud_types else "  - Unknown"
    reasons_text     = "\n".join(f"  - {r}"  for r in reasons)      if reasons      else "  - No specific reasons captured"

    prompt = f"""
You are a healthcare fraud investigation expert with deep knowledge
of medical billing, Medicare policies, and clinical practice standards.

================================================================
TRANSACTION DETAILS:
================================================================
Patient ID    : {transaction.get('PATIENT_ID')}
Doctor ID     : {transaction.get('DOCTOR_ID')}
Speciality    : {transaction.get('SPECIALITY_NAME')}
Diagnosis     : {transaction.get('DIAGNOSIS')}
Service       : {transaction.get('SERVICE_DESCRIPTION')}
Service ID    : {transaction.get('SERVICE_ID')}
Overall Verdict: {overall_risk}
Confidence    : {confidence * 100:.1f}%

================================================================
CROSS-FEATURE SIGNALS:
================================================================
doc_spec_match : {doc_spec}  → {feat_label(doc_spec)}
svc_spec_match : {svc_spec}  → {feat_label(svc_spec)}
diag_svc_match : {diag_svc}  → {feat_label(diag_svc)}

================================================================
INVESTIGATION FINDINGS:
================================================================
Responsible Party : {responsible_party}
Primary Fraud Type: {primary_fraud_type}
All Fraud Types:
{fraud_types_text}
Reasons:
{reasons_text}
Overbilling Flag  : {overbilling_flag}
{f"Overbilling Note: {overbilling_note}" if overbilling_flag else ""}

================================================================
DOCTOR ACCOUNTABILITY:
================================================================
Previous Fraud Count : {previous_frauds}
Penalty Applied      : -{score_penalty} points
Updated Score        : {doctor_score} / 100
Doctor Status        : {score_status}

================================================================
RELEVANT POLICIES (FAISS + GRAPH RAG):
================================================================
{retrieved_policies}

================================================================
GRAPH RAG — SPECIALTY MISMATCH RULE:
================================================================
Check GRAPH RAG CONTEXT above. Apply ONLY to specialty-service
mismatch evaluation — everything else stays the same:

CASE 1 — Service ALLOWED via direct CAN_ORDER:
  → No specialty mismatch exists
  → Evaluate fraud on all other signals only

CASE 2 — Service ALLOWED via INHERITS (General Physician):
  → Specialty mismatch is NOT fraud evidence
  → Do NOT mention specialty mismatch as fraud reason
  → Evaluate ALL OTHER fraud signals normally:
    (doctor history, overbilling, diagnosis mismatch etc.)
  → Other signals fraudulent → VERDICT: FRAUDULENT
  → Only specialty mismatch was concern → VERDICT: INVESTIGATE

CASE 3 — Service NOT FOUND (neither direct nor inherited):
  → Specialty mismatch IS valid fraud evidence
  → Combined with other signals → VERDICT: FRAUDULENT

IMPORTANT: This rule is ONLY for specialty-service mismatch.
Doctor history, overbilling, diagnosis mismatch, billing
patterns — all evaluated exactly the same as before.
================================================================

YOUR TASK:
Write a complete fraud investigation report. Use Graph RAG
ONLY for specialty-service mismatch. Everything else same.

Do NOT mention AI models, machine learning, GAN scores,
or detection systems.

Respond in this EXACT format:

VERDICT: [FRAUDULENT / INVESTIGATE / LEGITIMATE]

EXECUTIVE SUMMARY:
[2-3 sentences: who, what, and key finding]

TRANSACTION ANALYSIS:
[Clinical appropriateness + Graph RAG service permission finding]

CLINICAL ANALYSIS:
[Explain each signal in plain clinical language.
If service inherited, note specialty mismatch is not fraud.]

INVESTIGATION FINDINGS:
[Responsible party, fraud type, billing irregularities.
If only specialty mismatch and service is inherited —
not sufficient fraud evidence alone.]

POLICY VIOLATIONS:
[Which policies violated? If service inherited —
no specialty mismatch violation — focus on others only.]

OVERBILLING ASSESSMENT:
[Overbilling based on billing pattern?]

DOCTOR ACCOUNTABILITY:
[Penalty and current standing.]

RECOMMENDATION: [REJECT & INVESTIGATE FURTHER / INVESTIGATE / APPROVE]

ACTION ITEMS:
[3 specific actions for investigators]


IMPORTANT DISCLAIMER:

This report has been generated by an AI-based fraud detection
system and is intended for informational purposes only.

A qualified human reviewer must:
- Review this report carefully
- Verify all findings independently
- Make the final determination on whether fraud has occurred
- Approve, reject, or escalate this claim accordingly

This AI report does NOT constitute a final fraud verdict.
Final authority rests with the human reviewer only.
================================================================
"""

    print("Calling Groq API — fraud investigation report...")
    response = client.chat.completions.create(
        model      = "llama-3.3-70b-versatile",
        max_tokens = 1800,
        messages   = [
            {
                "role"   : "system",
                "content": (
                    "You are a healthcare fraud investigation expert. "
                    "For specialty-service mismatch: always check Graph RAG "
                    "context first. If service is inherited from General "
                    "Physician, do NOT use specialty mismatch as fraud evidence. "
                    "All other fraud signals — doctor history, overbilling, "
                    "diagnosis mismatch — evaluated exactly the same as before. "
                    "Never mention AI models, machine learning, GAN scores, "
                    "or any detection system."
                )
            },
            {"role": "user", "content": prompt}
        ]
    )

    report = response.choices[0].message.content
    print(f"✅ Fraud investigation report generated ({len(report)} chars)")
    print("\n" + "="*55)
    print("REPORT:")
    print("="*55)
    print(report)
    return report